// const Sequelize = require('sequelize');
//
// const { BillingRate } = require('../schema/billingSchema.js');

const seeds = [
  { country: "Afghanistan",	basic_rate: 20,	expedited_rate: 23,	one_day_rate: 26 },
  { country: "Albania",	basic_rate: 20,	expedited_rate: 23,	one_day_rate: 26 },
  { country: "Algeria",	basic_rate: 20,	expedited_rate: 23,	one_day_rate: 26 },
  { country: "Andorra",	basic_rate: 20,	expedited_rate: 23,	one_day_rate: 26 },
  { country: "Angola",	basic_rate: 20,	expedited_rate: 23,	one_day_rate: 26 },
  { country: "Antigua and Barbud",	basic_rate: 20,	expedited_rate: 23,	one_day_rate: 26 },
  { country: "Argentina",	basic_rate: 15,	expedited_rate: 18,	one_day_rate: 21 },
  { country: "Armenia",	basic_rate: 20,	expedited_rate: 23,	one_day_rate: 26 },
  { country: "Australia",	basic_rate: 15,	expedited_rate: 18,	one_day_rate: 21 },
  { country: "Austria",	basic_rate: 15,	expedited_rate: 18,	one_day_rate: 21 },
  { country: "Azerbaijan",	basic_rate: 20,	expedited_rate: 23,	one_day_rate: 26 },
  { country: "Bahamas",	basic_rate: 15,	expedited_rate: 18,	one_day_rate: 21 },
  { country: "Bahrain",	basic_rate: 20,	expedited_rate: 23,	one_day_rate: 26 },
  { country: "Bangladesh",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Barbados",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Belarus",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Belgium",	basic_rate: 20,	expedited_rate: 23,	one_day_rate: 26 },
  { country: "Belize",	basic_rate: 20,	expedited_rate: 23,	one_day_rate: 26 },
  { country: "Benin",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Bhutan",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Bolivia",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Bosnia and Herzegovina",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Botswana",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Brazil",	basic_rate: 15,	expedited_rate: 18,	one_day_rate: 21 },
  { country: "Brunei",	basic_rate: 20,	expedited_rate: 23,	one_day_rate: 26 },
  { country: "Bulgaria",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Burkina Faso",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Burundi",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Côte d'Ivoire",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Cabo Verde",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Cambodia",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Cameroon",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Canada",	basic_rate: 10,	expedited_rate: 13,	one_day_rate: 16 },
  { country: "Central African Republic",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Chad",	basic_rate: 30,	expedited_rate: 33,	one_day_rate: 36 },
  { country: "Chile",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "China",	basic_rate: 15,	expedited_rate: 18,	one_day_rate: 21 },
  { country: "Colombia",	basic_rate: 20,	expedited_rate: 23,	one_day_rate: 26 },
  { country: "Comoros",	basic_rate: 30,	expedited_rate: 33,	one_day_rate: 36 },
  { country: "Congo (Congo-Brazzaville)",	basic_rate: 30,	expedited_rate: 33,	one_day_rate: 36 },
  { country: "Costa Rica",	basic_rate: 20,	expedited_rate: 23,	one_day_rate: 26 },
  { country: "Croatia",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Cuba",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Cyprus",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Czech Republic",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Democratic Republic of the Congo",	basic_rate: 30,	expedited_rate: 33,	one_day_rate: 36 },
  { country: "Denmark",	basic_rate: 15,	expedited_rate: 18,	one_day_rate: 21 },
  { country: "Djibouti",	basic_rate: 30,	expedited_rate: 33,	one_day_rate: 36 },
  { country: "Dominica",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Dominican Republic",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Ecuador",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Egypt",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "El Salvador",	basic_rate: 30,	expedited_rate: 33,	one_day_rate: 36 },
  { country: "Equatorial Guinea",	basic_rate: 30,	expedited_rate: 33,	one_day_rate: 36 },
  { country: "Eritrea",	basic_rate: 30,	expedited_rate: 33,	one_day_rate: 36 },
  { country: "Estonia",	basic_rate: 30,	expedited_rate: 33,	one_day_rate: 36 },
  { country: "Ethiopia",	basic_rate: 30,	expedited_rate: 33,	one_day_rate: 36 },
  { country: "Fiji",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Finland",	basic_rate: 20,	expedited_rate: 23,	one_day_rate: 26 },
  { country: "France",	basic_rate: 15,	expedited_rate: 18,	one_day_rate: 21 },
  { country: "Gabon",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Gambia",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Georgia",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Germany",	basic_rate: 15,	expedited_rate: 18,	one_day_rate: 21 },
  { country: "Ghana",	basic_rate: 15,	expedited_rate: 18,	one_day_rate: 21 },
  { country: "Greece",	basic_rate: 15,	expedited_rate: 18,	one_day_rate: 21 },
  { country: "Grenada",	basic_rate: 20,	expedited_rate: 23,	one_day_rate: 26 },
  { country: "Guatemala",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Guinea",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Guinea-Bissau",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Guyana",	basic_rate: 30,	expedited_rate: 33,	one_day_rate: 36 },
  { country: "Haiti",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Holy See",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Honduras",	basic_rate: 20,	expedited_rate: 23,	one_day_rate: 26 },
  { country: "Hungary",	basic_rate: 20,	expedited_rate: 23,	one_day_rate: 26 },
  { country: "Iceland",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "India",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Indonesia",	basic_rate: 15,	expedited_rate: 18,	one_day_rate: 21 },
  { country: "Iran",	basic_rate: 30,	expedited_rate: 33,	one_day_rate: 36 },
  { country: "Iraq",	basic_rate: 30,	expedited_rate: 33,	one_day_rate: 36 },
  { country: "Ireland",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Israel",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Italy",	basic_rate: 20,	expedited_rate: 23,	one_day_rate: 26 },
  { country: "Jamaica",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Japan",	basic_rate: 15,	expedited_rate: 18,	one_day_rate: 21 },
  { country: "Jordan",	basic_rate: 20,	expedited_rate: 23,	one_day_rate: 26 },
  { country: "Kazakhstan",	basic_rate: 20,	expedited_rate: 23,	one_day_rate: 26 },
  { country: "Kenya",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Kiribati",	basic_rate: 30,	expedited_rate: 33,	one_day_rate: 36 },
  { country: "Kuwait",	basic_rate: 30,	expedited_rate: 33,	one_day_rate: 36 },
  { country: "Kyrgyzstan",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Laos",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Latvia",	basic_rate: 30,	expedited_rate: 33,	one_day_rate: 36 },
  { country: "Lebanon",	basic_rate: 20,	expedited_rate: 23,	one_day_rate: 26 },
  { country: "Lesotho",	basic_rate: 30,	expedited_rate: 33,	one_day_rate: 36 },
  { country: "Liberia",	basic_rate: 30,	expedited_rate: 33,	one_day_rate: 36 },
  { country: "Libya",	basic_rate: 30,	expedited_rate: 33,	one_day_rate: 36 },
  { country: "Liechtenstein",	basic_rate: 30,	expedited_rate: 33,	one_day_rate: 36 },
  { country: "Lithuania",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Luxembourg",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Macedonia (FYROM)",	basic_rate: 30,	expedited_rate: 33,	one_day_rate: 36 },
  { country: "Madagascar",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Malawi",	basic_rate: 30,	expedited_rate: 33,	one_day_rate: 36 },
  { country: "Malaysia",	basic_rate: 15,	expedited_rate: 18,	one_day_rate: 21 },
  { country: "Maldives",	basic_rate: 15,	expedited_rate: 18,	one_day_rate: 21 },
  { country: "Mali",	basic_rate: 15,	expedited_rate: 18,	one_day_rate: 21 },
  { country: "Malta",	basic_rate: 15,	expedited_rate: 18,	one_day_rate: 21 },
  { country: "Marshall Islands",	basic_rate: 20,	expedited_rate: 23,	one_day_rate: 26 },
  { country: "Mauritania",	basic_rate: 20,	expedited_rate: 23,	one_day_rate: 26 },
  { country: "Mauritius",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Mexico",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Micronesia",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Moldova",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Monaco",	basic_rate: 20,	expedited_rate: 23,	one_day_rate: 26 },
  { country: "Mongolia",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Montenegro",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Morocco",	basic_rate: 20,	expedited_rate: 23,	one_day_rate: 26 },
  { country: "Mozambique",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Myanmar (formerly Burma)",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Namibia",	basic_rate: 30,	expedited_rate: 33,	one_day_rate: 36 },
  { country: "Nauru",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Nepal",	basic_rate: 20,	expedited_rate: 23,	one_day_rate: 26 },
  { country: "Netherlands",	basic_rate: 20,	expedited_rate: 23,	one_day_rate: 26 },
  { country: "New Zealand",	basic_rate: 15,	expedited_rate: 18,	one_day_rate: 21 },
  { country: "Nicaragua",	basic_rate: 30,	expedited_rate: 33,	one_day_rate: 36 },
  { country: "Niger",	basic_rate: 30,	expedited_rate: 33,	one_day_rate: 36 },
  { country: "Nigeria",	basic_rate: 30,	expedited_rate: 33,	one_day_rate: 36 },
  { country: "North Korea",	basic_rate: 30,	expedited_rate: 33,	one_day_rate: 36 },
  { country: "Norway",	basic_rate: 15,	expedited_rate: 18,	one_day_rate: 21 },
  { country: "Oman",	basic_rate: 20,	expedited_rate: 23,	one_day_rate: 26 },
  { country: "Pakistan",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Palau",	basic_rate: 20,	expedited_rate: 23,	one_day_rate: 26 },
  { country: "Palestine State",	basic_rate: 20,	expedited_rate: 23,	one_day_rate: 26 },
  { country: "Panama",	basic_rate: 20,	expedited_rate: 23,	one_day_rate: 26 },
  { country: "Papua New Guinea",	basic_rate: 20,	expedited_rate: 23,	one_day_rate: 26 },
  { country: "Paraguay",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Peru",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Philippines",	basic_rate: 15,	expedited_rate: 18,	one_day_rate: 21 },
  { country: "Poland",	basic_rate: 20,	expedited_rate: 23,	one_day_rate: 26 },
  { country: "Portugal",	basic_rate: 15,	expedited_rate: 18,	one_day_rate: 21 },
  { country: "Qatar",	basic_rate: 20,	expedited_rate: 23,	one_day_rate: 26 },
  { country: "Romania",	basic_rate: 15,	expedited_rate: 18,	one_day_rate: 21 },
  { country: "Russia",	basic_rate: 15,	expedited_rate: 18,	one_day_rate: 21 },
  { country: "Rwanda",	basic_rate: 30,	expedited_rate: 33,	one_day_rate: 36 },
  { country: "Saint Kitts and Nevis",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Saint Lucia",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Saint Vincent and the Grenadines",	basic_rate: 20,	expedited_rate: 23,	one_day_rate: 26 },
  { country: "Samoa",	basic_rate: 20,	expedited_rate: 23,	one_day_rate: 26 },
  { country: "San Marino",	basic_rate: 20,	expedited_rate: 23,	one_day_rate: 26 },
  { country: "Sao Tome and Principe",	basic_rate: 20,	expedited_rate: 23,	one_day_rate: 26 },
  { country: "Saudi Arabia",	basic_rate: 20,	expedited_rate: 23,	one_day_rate: 26 },
  { country: "Senegal",	basic_rate: 20,	expedited_rate: 23,	one_day_rate: 26 },
  { country: "Serbia",	basic_rate: 20,	expedited_rate: 23,	one_day_rate: 26 },
  { country: "Seychelles",	basic_rate: 20,	expedited_rate: 23,	one_day_rate: 26 },
  { country: "Sierra Leone",	basic_rate: 20,	expedited_rate: 23,	one_day_rate: 26 },
  { country: "Singapore",	basic_rate: 10,	expedited_rate: 13,	one_day_rate: 16 },
  { country: "Slovakia",	basic_rate: 15,	expedited_rate: 18,	one_day_rate: 21 },
  { country: "Slovenia",	basic_rate: 15,	expedited_rate: 18,	one_day_rate: 21 },
  { country: "Solomon Islands",	basic_rate: 15,	expedited_rate: 18,	one_day_rate: 21 },
  { country: "Somalia",	basic_rate: 15,	expedited_rate: 18,	one_day_rate: 21 },
  { country: "South Africa",	basic_rate: 20,	expedited_rate: 23,	one_day_rate: 26 },
  { country: "South Korea",	basic_rate: 15,	expedited_rate: 18,	one_day_rate: 21 },
  { country: "South Sudan",	basic_rate: 30,	expedited_rate: 33,	one_day_rate: 36 },
  { country: "Spain",	basic_rate: 15,	expedited_rate: 18,	one_day_rate: 21 },
  { country: "Sri Lanka",	basic_rate: 20,	expedited_rate: 23,	one_day_rate: 26 },
  { country: "Sudan",	basic_rate: 30,	expedited_rate: 33,	one_day_rate: 36 },
  { country: "Suriname",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Swaziland",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Sweden",	basic_rate: 10,	expedited_rate: 13,	one_day_rate: 16 },
  { country: "Switzerland",	basic_rate: 10,	expedited_rate: 13,	one_day_rate: 16 },
  { country: "Syria",	basic_rate: 30,	expedited_rate: 33,	one_day_rate: 36 },
  { country: "Tajikistan",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Tanzania",	basic_rate: 20,	expedited_rate: 23,	one_day_rate: 26 },
  { country: "Thailand",	basic_rate: 15,	expedited_rate: 18,	one_day_rate: 21 },
  { country: "Timor-Leste",	basic_rate: 15,	expedited_rate: 18,	one_day_rate: 21 },
  { country: "Togo",	basic_rate: 20,	expedited_rate: 23,	one_day_rate: 26 },
  { country: "Tonga",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Trinidad and Tobago",	basic_rate: 15,	expedited_rate: 18,	one_day_rate: 21 },
  { country: "Tunisia",	basic_rate: 15,	expedited_rate: 18,	one_day_rate: 21 },
  { country: "Turkey",	basic_rate: 15,	expedited_rate: 18,	one_day_rate: 21 },
  { country: "Turkmenistan",	basic_rate: 15,	expedited_rate: 18,	one_day_rate: 21 },
  { country: "Tuvalu",	basic_rate: 20,	expedited_rate: 23,	one_day_rate: 26 },
  { country: "Uganda",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Ukraine",	basic_rate: 15,	expedited_rate: 18,	one_day_rate: 21 },
  { country: "United Arab Emirates",	basic_rate: 20,	expedited_rate: 23,	one_day_rate: 26 },
  { country: "United Kingdom",	basic_rate: 10,	expedited_rate: 13,	one_day_rate: 16 },
  { country: "United States of America",	basic_rate: 10,	expedited_rate: 13,	one_day_rate: 16 },
  { country: "Uruguay",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Uzbekistan",	basic_rate: 30,	expedited_rate: 33,	one_day_rate: 36 },
  { country: "Vanuatu",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Venezuela",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Viet Nam",	basic_rate: 15,	expedited_rate: 18,	one_day_rate: 21 },
  { country: "Yemen",	basic_rate: 20,	expedited_rate: 23,	one_day_rate: 26 },
  { country: "Zambia",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 },
  { country: "Zimbabwe",	basic_rate: 25,	expedited_rate: 28,	one_day_rate: 31 }
];

const zips = [
  {zip: 94027, city: "Atherton", state: "CA"},
  {zip: 90210, city: "Beverly Hills", state: "CA"},
  {zip: 90402, city: "Santa Monica", state: "CA"},
  {zip: 94301, city: "Palo Alto", state: "CA"},
  {zip: 94022, city: "Los Altos", state: "CA"},
  {zip: 94957, city: "Ross", state: "CA"},
  {zip: 92657, city: "Newport Coast", state: "CA"},
  {zip: 94028, city: "Portola Valley", state: "CA"},
  {zip: 94024, city: "Los Altos", state: "CA"},
  {zip: 92661, city: "Newport Beach", state: "CA"},
  {zip: 93108, city: "Santa Barbara", state: "CA"},
  {zip: 90272, city: "Los Angeles", state: "CA"},
  {zip: 94528, city: "Diablo", state: "CA"},
  {zip: 94303, city: "Palo Alto", state: "CA"},
  {zip: 92662, city: "Newport Beach", state: "CA"},
  {zip: 94920, city: "Belvedere", state: "CA"},
  {zip: 90265, city: "Malibu", state: "CA"},
  {zip: 94306, city: "Palo Alto", state: "CA"},
  {zip: 94010, city: "Burlingame", state: "CA"},
  {zip: 95070, city: "Saratoga", state: "CA"},
  {zip: 90266, city: "Manhattan Beach", state: "CA"},
  {zip: 95030, city: "Los Gatos", state: "CA"},
  {zip: 92067, city: "Rancho Santa Fe", state: "CA"},
  {zip: 94305, city: "Stanford", state: "CA"},
  {zip: 91108, city: "San Marino", state: "CA"},
  {zip:  2625,  city: "Corona Del Mar", state: "CA"},
  {zip: 90077, city: "Los Angeles", state: "CA"},
  {zip: 94025, city: "Menlo Park", state: "CA"},
  {zip: 90212, city: "Beverly Hills", state: "CA"},
  {zip: 90049, city: "Los Angeles", state: "CA"},
  {zip: 94118, city: "San Francisco", state: "CA"},
  {zip: 94104, city: "San Francisco", state: "CA"},
  {zip: 94123, city: "San Francisco", state: "CA"},
  {zip: 92651, city: "Laguna Beach", state: "CA"},
  {zip: 94939, city: "Larkspur", state: "CA"},
  {zip: 94087, city: "Sunnyvale", state: "CA"},
  {zip: 95014, city: "Cupertino", state: "CA"},
  {zip: 94041, city: "Mountain View", state: "CA"},
  {zip: 90291, city: "Venice", state: "CA"},
  {zip: 90742, city: "Sunset Beach", state: "CA"},
  {zip: 94402, city: "San Mateo", state: "CA"},
  {zip: 94062, city: "Redwood City", state: "CA"},
  {zip: 92660, city: "Newport Beach", state: "CA"},
  {zip: 94040, city: "Mountain View", state: "CA"},
  {zip: 93953, city: "Pebble Beach", state: "CA"},
  {zip: 94114, city: "San Francisco", state: "CA"},
  {zip: 94970, city: "Stinson Beach", state: "CA"},
  {zip: 91011, city: "La Canada Flintridge", state: "CA"},
  {zip: 95032, city: "Los Gatos", state: "CA"},
  {zip: 94070, city: "San Carlos", state: "CA"},
  {zip: 94127, city: "San Francisco", state: "CA"},
  {zip: 93921, city: "Carmel By The Sea", state: "CA"},
  {zip: 92663, city: "Newport Beach", state: "CA"},
  {zip: 94904, city: "Greenbrae", state: "CA"},
  {zip: 94002, city: "Belmont", state: "CA"},
  {zip: 94133, city: "San Francisco", state: "CA"},
  {zip: 94507, city: "Alamo", state: "CA"},
  {zip: 90274, city: "Palos Verdes Peninsula", state: "CA"},
  {zip: 90254, city: "Hermosa Beach", state: "CA"},
  {zip: 90405, city: "Santa Monica", state: "CA"},
  {zip: 91008, city: "Duarte", state: "CA"},
  {zip: 91436, city: "Encino", state: "CA"},
  {zip: 94117, city: "San Francisco", state: "CA"},
  {zip: 95129, city: "San Jose", state: "CA"},
  {zip: 94705, city: "Berkeley", state: "CA"},
  {zip: 94030, city: "Millbrae", state: "CA"},
  {zip: 90036, city: "Los Angeles", state: "CA"},
  {zip: 90048, city: "Los Angeles", state: "CA"},
  {zip: 94061, city: "Redwood City", state: "CA"},
  {zip: 94563, city: "Orinda", state: "CA"},
  {zip: 92014, city: "Del Mar", state: "CA"},
  {zip: 94707, city: "Berkeley", state: "CA"},
  {zip: 94121, city: "San Francisco", state: "CA"},
  {zip: 92118, city: "Coronado", state: "CA"},
  {zip: 94115, city: "San Francisco", state: "CA"},
  {zip: 95120, city: "San Jose", state: "CA"},
  {zip: 94549, city: "Lafayette", state: "CA"},
  {zip: 81611, city: "Aspen", state: "CO"},
  {zip: 06878, city: "Riverside", state: "CT"},
  {zip: 06830, city: "Greenwich", state: "CT"},
  {zip: 33109, city: "Miami Beach", state: "FL"},
  {zip: 33921, city: "Boca Grande", state: "FL"},
  {zip: 96821, city: "Honolulu", state: "HI"},
  {zip: 02108, city: "Boston", state: "MA"},
  {zip: 02481, city: "Wellesley Hills", state: "MA"},
  {zip: 21056, city: "Gibson Island", state: "MD"},
  {zip: 07620, city: "Alpine", state: "NJ"},
  {zip: 07078, city: "Short Hills", state: "NJ"},
  {zip: 89413, city: "Glenbrook", state: "NV"},
  {zip: 10013, city: "New York", state: "NY"},
  {zip: 10007, city: "New York", state: "NY"},
  {zip: 11976, city: "Water Mill", state: "NY"},
  {zip: 11975, city: "Wainscott", state: "NY"},
  {zip: 11962, city: "Sagaponack", state: "NY"},
  {zip: 10282, city: "New York", state: "NY"},
  {zip: 10006, city: "New York", state: "NY"},
  {zip: 11932, city: "Bridgehampton", state: "NY"},
  {zip: 10069, city: "New York", state: "NY"},
  {zip: 11568, city: "Old Westbury", state: "NY"},
  {zip: 10012, city: "New York", state: "NY"},
  {zip: 10580, city: "Rye", state: "NY"},
  {zip: 11930, city: "Amagansett", state: "NY"},
  {zip: 11030, city: "Manhasset", state: "NY"},
  {zip: 11024, city: "Great Neck", state: "NY"},
  {zip: 11765, city: "Mill Neck", state: "NY"},
  {zip: 10024, city: "New York", state: "NY"},
  {zip: 11959, city: "Quogue", state: "NY"},
  {zip: 11963, city: "Sag Harbor", state: "NY"},
  {zip: 98039, city: "Medina", state: "WA"},
  {zip: 98004, city: "Bellevue", state: "WA"}
];

module.exports = {
  seeds: seeds,
  zips: zips
};
